#!/usr/bin/zsh

#zmodload zsh/zprof
export ZSHRC="$HOME/.zshrc"
export ZSH_BASE="$(dirname "$(readlink -f "$ZSHRC")")"

export DISABLE_UPDATE_PROMPT=true
export DISABLE_AUTO_UPDATE=true
export DEFAULT_USER=p-himik

# There're problems with user sites and conda
# e.g. https://github.com/conda/conda/issues/448
export PYTHONNOUSERSITE=True

# Lines configured by zsh-newuser-install
export HISTFILE=~/.histfile
export HISTSIZE=1000
export SAVEHIST=1000
export HIST_STAMPS="dd.mm.yyyy"
# End of lines configured by zsh-newuser-install

# Remember also to execute
# conda config --set changeps1 false
export VIRTUAL_ENV_DISABLE_PROMPT=true

if [[ -n "$ANACONDA_HOME" && -e "$ANACONDA_HOME/etc/profile.d/conda.sh" ]]; then
    . "$ANACONDA_HOME/etc/profile.d/conda.sh"
elif [[ -n "$MINICONDA_HOME" && -e "$MINICONDA_HOME/etc/profile.d/conda.sh" ]]; then
    . "$MINICONDA_HOME/etc/profile.d/conda.sh"
fi

source "$ZSH_BASE/zgen/zgen.zsh"

if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/gitfast
    zgen oh-my-zsh plugins/svn
    zgen oh-my-zsh plugins/colored-man-pages
    zgen oh-my-zsh plugins/jump
    zgen oh-my-zsh plugins/extract
    zgen oh-my-zsh plugins/virtualenv
    zgen oh-my-zsh plugins/zsh_reload
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/vagrant
    zgen oh-my-zsh plugins/pyenv
    zgen oh-my-zsh plugins/dotenv

    zgen load khrt/svn-n-zsh-plugin
    zgen load zdharma/fast-syntax-highlighting
    zgen load zsh-users/zsh-history-substring-search
    zgen load rimraf/k
    zgen load arialdomartini/oh-my-git
    zgen load scmbreeze/scm_breeze scm_breeze.sh
    zgen load ingydotnet/git-subrepo .rc

    zgen load docker/compose contrib/completion/zsh/_docker-compose 1.21.0
    zgen load docker/machine contrib/completion/zsh/_docker-machine v0.16.1
    zgen load containers/libpod completions/zsh/_podman master

    zgen load "$ZSH_BASE/themes/p-himik"
    zgen load "$ZSH_BASE/my_mvn.zsh"
    zgen load "$ZSH_BASE/aliases.zsh"
    zgen load "$ZSH_BASE/line_numbers.zsh"
    zgen load "$ZSH_BASE/git_functions.zsh"  # loading after SCM Breeze to override some aliases
    zgen load "$ZSH_BASE/conda_env.zsh"

    zgen save
fi

function omg-description() {
    for i in $(typeset + | grep "^omg_.*_symbol$"); do
        local s="${(P)i}"
        local color_var="${i}_color"
        local color="${(P)color_var}"
        local desc="$(echo $i | sed -r 's/^omg_(.*)_symbol$/\1/g' | tr '_' ' ')"
        print -P -- "${color} ${s} %k%b - ${desc}"
    done
}

unsetopt extendedglob sharehistory
setopt incappendhistory autocd

compctl -K listMavenCompletions mvn2
compctl -K listMavenCompletions mvn3

#set -o vi
#bindkey -v

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind k and j for VI mode for history-substring-search
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored _approximate _prefix
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*'
zstyle ':completion:*' max-errors 1
zstyle ':completion:*' prompt 'No completion found. Corrected results:'
zstyle :compinstall filename "$ZSHRC"
# End of lines added by compinstall

export FZF_DEFAULT_OPTS="--inline-info -e --ansi --history-size=100000 --bind=tab:accept,ctrl-m:toggle+down,ctrl-alt-m:toggle+up"
export FZF_DEFAULT_COMMAND='env MESSAGELANG=C fd --type file --color=always'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [[ $1 == eval ]]
then
    "$@"
    set --
fi
#zprof

