#!/usr/bin/zsh

# Use to add timestamps to `set -x` output.
# PS4='+ $(date "+%s.%N")\011 '

#zmodload zsh/zprof
export ZSHRC="$HOME/.zshrc"
export ZSH_BASE="$(dirname "$(readlink -f "$ZSHRC")")"

export DISABLE_UPDATE_PROMPT=true
export DISABLE_AUTO_UPDATE=true
export DEFAULT_USER=p-himik

# Lines configured by zsh-newuser-install
export HISTFILE=~/.histfile
export HISTSIZE=100000
export SAVEHIST=100000
export HIST_STAMPS="dd.mm.yyyy"
# End of lines configured by zsh-newuser-install

export VIRTUAL_ENV_DISABLE_PROMPT=true

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

source "$ZSH_BASE/zgen/zgen.zsh"

if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/gitfast
    zgen oh-my-zsh plugins/svn
    zgen oh-my-zsh plugins/colored-man-pages
    zgen oh-my-zsh plugins/jump
    zgen oh-my-zsh plugins/extract
    zgen oh-my-zsh plugins/virtualenv
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/dotenv
    # Disabling pyenv because it makes the prompt appear much slower.
    #zgen oh-my-zsh plugins/pyenv

    zgen load khrt/svn-n-zsh-plugin
    zgen load z-shell/F-Sy-H . main
    zgen load zsh-users/zsh-history-substring-search
    zgen load rimraf/k
    zgen load scmbreeze/scm_breeze scm_breeze.sh
    zgen load ingydotnet/git-subrepo .rc

    zgen load containers/podman completions/zsh/_podman main

    zgen load "$ZSH_BASE/themes/p-himik"
    zgen load "$ZSH_BASE/my_mvn.zsh"
    zgen load "$ZSH_BASE/aliases.zsh"
    zgen load "$ZSH_BASE/line_numbers.zsh"
    zgen load "$ZSH_BASE/git_functions.zsh"  # loading after SCM Breeze to override some aliases

    zgen save
fi

unsetopt sharehistory
setopt incappendhistory autocd extendedglob

compctl -K listMavenCompletions mvn2
compctl -K listMavenCompletions mvn3

#set -o vi
#bindkey -v

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind k and j for VI mode for history-substring-search
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored _approximate _prefix
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*'
zstyle ':completion:*' max-errors 1
zstyle ':completion:*' prompt 'No completion found. Corrected results:'
zstyle :compinstall filename "$ZSHRC"
# End of lines added by compinstall

export FZF_DEFAULT_OPTS="--inline-info -e --ansi --history-size=100000 --bind=tab:accept,ctrl-m:toggle+down,ctrl-alt-m:toggle+up"
export FZF_DEFAULT_COMMAND='env MESSAGELANG=C fd --type file --color=always'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [[ $1 == eval ]]
then
    "$@"
    set --
fi
#zprof


PATH="/home/p-himik/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/p-himik/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/p-himik/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/p-himik/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/p-himik/perl5"; export PERL_MM_OPT;

# Added by ProtonUp-Qt on 03-10-2022 23:49:36
if [ -d "/home/p-himik/stl/prefix" ]; then export PATH="$PATH:/home/p-himik/stl/prefix"; fi
